backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

local_backend: true
# publish_mode: editorial_workflow   # optional

collections:
  - name: "settings"
    label: "Site Settings"
    delete: false
    format: "json"
    files:
      - name: "settings"
        label: "Global Settings"
        file: "content/settings.json"
        fields:
          # --- Text/meta ---
          - { label: "Site Title",    name: "siteTitle",   widget: "string" }
          - { label: "Tagline",       name: "tagline",     widget: "string", required: false }

          # --- Images (UNIQUE names) ---
          - { label: "Hero Image",        name: "heroImage",     widget: "image", required: false }
          - { label: "About Image",       name: "aboutImage",    widget: "image", required: false }
          - { label: "Concerts Image",    name: "concertsImage", widget: "image", required: false }
          - { label: "Contact Image",     name: "contactImage",  widget: "image", required: false }

          # --- Contact/social ---
          - { label: "Contact Email", name: "contactEmail", widget: "string", required: false }
          - { label: "Instagram URL", name: "instagram",    widget: "string", required: false }
          - { label: "Facebook URL",  name: "facebook",     widget: "string", required: false }

  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { name: "title",     label: "Title",     widget: "string" }
      - { name: "date",      label: "Date/Time (ISO)", widget: "datetime" }
      - { name: "venue",     label: "Venue",     widget: "string", required: false }
      - { name: "city",      label: "City",      widget: "string", required: false }
      - { name: "ticketUrl", label: "Ticket URL", widget: "string", required: false }
      - { name: "slug",      label: "Slug",      widget: "string", required: false }

  - name: "releases"
    label: "Releases"
    folder: "content/releases"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { name: "title",    label: "Title",    widget: "string" }
      - { name: "subtitle", label: "Subtitle", widget: "string", required: false }
      - { name: "cover",    label: "Cover Image", widget: "image", required: false }
      - label: "Links"
        name: "links"
        widget: "list"
        collapsed: true
        fields:
          - { name: "label", label: "Label", widget: "string" }
          - { name: "href",  label: "URL",   widget: "string" }
      - { name: "slug",     label: "Slug",   widget: "string", required: false }

  - name: "quotes"
    label: "Press Quotes"
    folder: "content/quotes"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { name: "outlet", label: "Outlet", widget: "string" }
      - { name: "text",   label: "Quote",  widget: "text" }
  - name: "about"
    label: "About (Official Biography)"
    delete: false
    format: "json"
    files:
      - name: "official"
        label: "Official Biography"
        file: "content/about.json"
        fields:
          - { name: "bioShort", label: "Short Bio (Markdown)", widget: "markdown", required: false }
          - { name: "bioLong",  label: "Official Bio (Markdown)", widget: "markdown" }
          - label: "Headshots"
            name: "headshots"
            widget: "list"
            fields:
              - { name: "src",    label: "Image", widget: "image" }
              - { name: "alt",    label: "Alt Text", widget: "string", required: false }
              - { name: "credit", label: "Credit", widget: "string", required: false }
          - { name: "pressKit", label: "Press Kit (PDF)", widget: "file", required: false }
